name: Cypress Tests

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run with dashboard recording
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/5-assertion.cy.js
          record: true
          group: 'GitHub Actions'
          tag: 'github'
        env:
          # Pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}

      - name: Upload artifacts on failure
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/**/*.mp4
            cypress/screenshots/**/*.png
          retention-days: 1
          if-no-files-found: ignore
